services:
  wikidocs:
    image: zavy86/wikidocs
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 8082:80
    volumes:
      - datasets-docs-cropco:/datasets
volumes: datasets-docs-cropco
